### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by N-Upchurch** [YunoHost-Apps/emailpoubelle_ynh#19]
### Describe the bug

500 Error - only header loads when accessing server.com/poubelle

### Context

- Hardware: VPS bought online
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Install with no public access and access URL.

**Comment by N-Upchurch** [comment]
Unfortunately using a pass with no special characters didn't help. When I go to https://URL/emailPoubelle.php, I receive the following message:

```
Debug enabled
Array ( ) 1
Error : the configuration file conf.php might not be included because the constants are not declared.
```

**Comment by Krakinou** [comment]
Hello,

Thanks for reporting, I've the same issue on my install.
I suppose some security hardenings on the yunohost side have broken this "very old" app.
Well give it a look this week.

**Comment by yalh76** [comment]
Have you tryed with last version ?

**Comment by N-Upchurch** [comment]
The issue doesn't seem to be present in the latest version; thanks!
