### ISSUE TITLE
Spelling error on no-reply email

### ISSUE THREAD

**Issue by deljones** [YunoHost-Apps/emailpoubelle_ynh#24]
Love this app…

Small detail…

the emails back to the user says:

[NO **REPLAY** emailPoubelle <xxxxxxxxxxx@xxxxxxxxxx.nohost.me>]

Spelling should be:

[NO **REPLY** emailPoubelle <xxxxxxxxxxx@xxxxxxxxxx.nohost.me>]

Great app all the same.

Sorry for not completing the issue properly, but it’s such a small, but important detail.

many thanks

dj

**Comment by Krakinou** [comment]
Hi!
Glad to see I'm not the only one using it :)
This is more of an upstream bug, you may open an issue there:
https://framagit.org/kepon/emailPoubellePhp
