### ISSUE TITLE
Why `poubelle` instead of `emailpoubelle` ? :D

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/emailpoubelle_ynh#5]
Hellow,

I'm not sure to understand why the repo was renamed to `poubelle` instead of `emailpoubelle` ... at least I'm noticing this in the context of checking the consistency between the name of the repo and the id in `manifest.json` ... for consistency it would be nice to have the repo named `emailpoubelle_ynh` :s

**Comment by Krakinou** [comment]
Hi,
At the beginning, I named it poubelle in order not to mix it with the existing one of matlink which was already called "emailpoubelle".
And then, you know, time goes and I just keep it...
I don't have access to change thee repo name now it's in Yunohost-Apps repo...

**Comment by alexAubin** [comment]
Brutally fixed it because I happen to be owner of the orga now ...
