### ISSUE TITLE
Instead of brutally editing the postfix conf, you should rely on the regenconf

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/emailpoubelle_ynh#6]
Hey there,

following a post on the forum about the app, I came to talk about a pretty much undocumented way of correctly extending service configuration such as postfix ;) 

You can do this by creating and adding custom "hooks" that shall be ran each time the regen-conf for postfix is ran for instance.

So for instance I did it here for mailman. I copied the hook to the "right" place : 

https://github.com/YunoHost-Apps/mailman_ynh/blob/master/scripts/install#L114

And the hook itself looks like this : 

https://github.com/YunoHost-Apps/mailman_ynh/blob/master/sources/hooks/conf_regen/98-postfix_mailman

Note that the file is called `98_postfix_mailman` which causes it to be triggered when the regenconf for posftix is done. So you could call your own something like `98_postfix_emailpoubelle`.

Then you can see in the actual hook code how I modify the *pending* postfix conf : `${pending_dir}/../postfix/etc/postfix/main.cf`. Do *not* modify directly `/etc/postfix/...` ... only the file in `$pending_dir`, except if you have a good reason / know what you're doing :wink:

**Comment by Krakinou** [comment]
Hi!
Emailpoubelle was the first app I packaged and looking how I did it make my eyes cry now :/
I plan to update it soon to kept up to date to packaging good practice.
As per the postfix part, I kept it from the original packager as I don't have the faintest idea of how postfix works...

However, I checked your code and will try to implement, but there is something I don't understand: where is the `${pending_dir}`defined? How is it pass to the hook and with which syntax?

**Comment by alexAubin** [comment]
>Anyway, I checked your code and will try to implement, but there is something I don't understand: where is the ${pending_dir}defined? How is it pass to the hook and with which syntax?

Weeeell, supposedly you don't really need to know that to implement it, the `$pending_dir` is just the folder where the pending "new" files are created / modified before being actually commited (or not) to the "real" filesystem. The "or not" relates to the fact that if the user manually modified some conf file, then the regen conf won't update it ;)

Anyway, it's created there during the regenconf : 

https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/service.py#L46
https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/service.py#L472

**Comment by Krakinou** [comment]
Done in 2.0~ynh4
